# Generated by Django 4.0.3 on 2022-03-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(max_length=200)),
                ('container_grade', models.DateTimeField(verbose_name='Gradacja Sprzętu')),
            ],
        ),
        migrations.CreateModel(
            name='PickUpDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.containertype')),
            ],
        ),
    ]
