# Generated by Django 4.0.3 on 2022-03-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdate',
            name='container',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.containertype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='containertype',
            name='container_grade',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pickupdate',
            name='date',
            field=models.DateTimeField(verbose_name='Data podjęcia kontenera'),
        ),
    ]
