# Generated by Django 4.0.3 on 2022-04-23 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_containertype_container_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerspec',
            name='container_grade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
