# Generated by Django 4.0.3 on 2022-03-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_pickupdate_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertype',
            name='container_grade',
            field=models.IntegerField(default=0),
        ),
    ]
