# Generated by Django 4.0.3 on 2022-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_containerspec_haulier_containerspec_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerspec',
            name='date',
            field=models.DateTimeField(default='YYYY-MM-DD', verbose_name='pick up date'),
        ),
        migrations.AlterField(
            model_name='containerspec',
            name='remarks',
            field=models.TextField(blank=True, default=None),
        ),
    ]
