# Generated by Django 4.0.3 on 2022-04-24 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_containerspec_date_alter_containerspec_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerspec',
            name='date',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='pick up date'),
        ),
    ]
